server:
  port: 9090
# 关闭缓存
spring:
  thymeleaf:
    cache: false
  #application:
   # name: es-demo
#eureka:
  #client:
   # service-url:
    #  defaultZone: http://localhost:8000/eureka/
  #instance:
   # prefer-ip-address: true
  ########################以下位redis增加配置##################
  redis:
    timeout: 6000
    # 单机配置
    #host: 127.0.0.1
    #port: 6379
    #########################以下为redis哨兵增加配置
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379
    lettuce:
      pool:
        max-active: 100 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 #连接池最大空闲连接
        min-idle: 50 #连接池最小空闲连接
        max-wait: 6000 #连接池最大阻塞等待时间（使用负值表示没有限制）
    password: ""
  ######################以下为springcache增加的配置
  cache:
    redis:
      use-key-prefix: true
      key-prefix: byterun-dev
      cache-null-values: false
      time-to-live: 20s
logging:
  config: classpath:logback-spring.xml